
# 서버 포트
server:
  port: 5000
---
# JSP
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    static-path-pattern: /static/**
---
# 실시간 반영 ( 정적 변동 시 )
spring:
  devtools:
    livereload:
      enabled: true
---
# ORACLE
spring:
  datasource:
    url: jdbc:oracle:thin:@dreamcapsule-db.cfzlzcz0pe0g.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: dreamcapsule
    password: dreamcap0902!

---
# mybatis 세팅
mybatis:
  type-aliases-package: com.dreamcapsule.project.domain
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

---
# static 정적 리소스 접근
spring:
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  mvc:
    static-path-pattern: /static/**

---
# ERROR 기본값 사용 안함
server:
  error:
    whitelabel:
      enabled: false
